# 9. Hafta Lab-1: Bagging
## BGM 565: Siber Güvenlik için Makine Öğrenme Yöntemleri
## İstanbul Şehir Üni. - Bilgi Güvenliği Müh.
### Dr. Ferhat Özgür Çatak
Bu lab çalışması kapsamında bagging yöntemi ile topluluk sınıflandırma modeli oluşturulacaktır.

In [1]:
from sklearn.datasets import make_classification
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
import numpy as np

#np.random.seed(22)

### Veri kümesi oluştur.

In [2]:
X, y = make_classification(n_samples=1000,n_features=2, n_redundant=0, n_informative=1,
                             n_clusters_per_class=1, class_sep=0.5)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

### 4 farklı sınıflandırma algoritması seçelim

In [3]:
names = ["Nearest Neighbors", "Linear SVM", "RBF SVM", "Decision Tree"]
classifiers = [
    KNeighborsClassifier(3),
    SVC(kernel="linear", C=0.025),
    SVC(gamma=2, C=1),
    DecisionTreeClassifier()]

### Sınıflandırma algoritmalarının tek başına performansları

In [4]:
for name, clf in zip(names, classifiers):
    print('-'*30)
    print("Algoritma:",name)
    clf.fit(X_train,y_train)
    y_test_pred = clf.predict(X_test)
    cm = confusion_matrix(y_test,y_test_pred)
    print('Egitim örnekleri')
    print(cm)

------------------------------
Algoritma: Nearest Neighbors
Egitim örnekleri
[[136  35]
 [ 37 122]]
------------------------------
Algoritma: Linear SVM
Egitim örnekleri
[[149  22]
 [ 35 124]]
------------------------------
Algoritma: RBF SVM
Egitim örnekleri
[[150  21]
 [ 34 125]]
------------------------------
Algoritma: Decision Tree
Egitim örnekleri
[[120  51]
 [ 46 113]]


### Bagging ile 4 farklı model oluşturalım

In [5]:
for name, clf in zip(names, classifiers):
    print('-'*40)
    print("Algoritma:",name)
    bagging_clf = BaggingClassifier( base_estimator=clf,
                                    n_estimators=500,
                                    max_samples=0.5,
                                    verbose=0)
    bagging_clf.fit(X_train,y_train)
    y_test_pred = bagging_clf.predict(X_test)
    cm = confusion_matrix(y_test,y_test_pred)
    print('Egitim örnekleri')
    print(cm)

----------------------------------------
Algoritma: Nearest Neighbors
Egitim örnekleri
[[146  25]
 [ 36 123]]
----------------------------------------
Algoritma: Linear SVM
Egitim örnekleri
[[149  22]
 [ 35 124]]
----------------------------------------
Algoritma: RBF SVM
Egitim örnekleri
[[150  21]
 [ 34 125]]
----------------------------------------
Algoritma: Decision Tree
Egitim örnekleri
[[148  23]
 [ 38 121]]
