# 9. Hafta Lab-2: Random Forest
## BGM 565: Siber Güvenlik için Makine Öğrenme Yöntemleri
## İstanbul Şehir Üni. - Bilgi Güvenliği Müh.
### Dr. Ferhat Özgür Çatak
Bu lab çalışması kapsamında *Random Forest* yöntemi ile topluluk sınıflandırma modeli oluşturulacaktır.

In [1]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn import tree
import numpy as np

np.random.seed(22)


### Veri kümesi oluştur.

In [2]:
X, y = make_classification(n_samples=10000,n_features=50, n_redundant=0, n_informative=1,
                             n_clusters_per_class=1, class_sep=0.5)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

### Karar ağacı algoritması sonuçları

In [3]:
clf = tree.DecisionTreeClassifier()
clf.fit(X_train, y_train)
y_test_pred = clf.predict(X_test)
cm = confusion_matrix(y_test, y_test_pred)
print(cm)

[[1492  136]
 [ 108 1564]]


### RandomForest Modelleri

In [6]:
ensemble_clfs = [
    ("RandomForestClassifier, max_features='sqrt'",
        RandomForestClassifier(max_features="sqrt", n_estimators=500, n_jobs=-1, verbose=1)),
    ("RandomForestClassifier, max_features='log2'",
        RandomForestClassifier( max_features='log2', n_estimators=500, n_jobs=-1, verbose=1)),
    ("RandomForestClassifier, max_features=None",
        RandomForestClassifier(max_features=None, n_estimators=500, n_jobs=-1, verbose=1))
]

### Farklı modellerin eğitimi

In [7]:
for label, clf in ensemble_clfs:
    print(label)
    clf.fit(X_train, y_train)
    y_test_pred = clf.predict(X_test)
    cm = confusion_matrix(y_test, y_test_pred)
    print(cm)

RandomForestClassifier, max_features='sqrt'


[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:    1.4s
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:    6.1s
[Parallel(n_jobs=-1)]: Done 442 tasks      | elapsed:   13.5s
[Parallel(n_jobs=-1)]: Done 500 out of 500 | elapsed:   15.4s finished
[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 192 tasks      | elapsed:    0.1s
[Parallel(n_jobs=4)]: Done 442 tasks      | elapsed:    0.3s
[Parallel(n_jobs=4)]: Done 500 out of 500 | elapsed:    0.3s finished


[[1618   10]
 [ 121 1551]]
RandomForestClassifier, max_features='log2'


[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:    0.8s
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:    4.1s
[Parallel(n_jobs=-1)]: Done 442 tasks      | elapsed:    9.9s
[Parallel(n_jobs=-1)]: Done 500 out of 500 | elapsed:   11.4s finished
[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 192 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 442 tasks      | elapsed:    0.2s
[Parallel(n_jobs=4)]: Done 500 out of 500 | elapsed:    0.3s finished


[[1618   10]
 [ 121 1551]]
RandomForestClassifier, max_features=None


[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:   13.5s
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done 442 tasks      | elapsed:  2.5min
[Parallel(n_jobs=-1)]: Done 500 out of 500 | elapsed:  2.8min finished
[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 192 tasks      | elapsed:    0.1s
[Parallel(n_jobs=4)]: Done 442 tasks      | elapsed:    0.3s


[[1605   23]
 [ 117 1555]]


[Parallel(n_jobs=4)]: Done 500 out of 500 | elapsed:    0.3s finished
