# 9. Hafta Lab-3: AdaBoost
## BGM 565: Siber Güvenlik için Makine Öğrenme Yöntemleri
## İstanbul Şehir Üni. - Bilgi Güvenliği Müh.
### Dr. Ferhat Özgür Çatak
Bu lab çalışması kapsamında *AdaBoost* yöntemi ile topluluk sınıflandırma modeli oluşturulacaktır.

In [1]:
from sklearn.datasets import make_classification
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier
import numpy as np

np.random.seed(22)

### Veri kümesi oluştur.

In [2]:
X, y = make_classification(n_samples=10000,n_features=2, n_redundant=0, n_informative=1,
                             n_clusters_per_class=1, class_sep=0.9)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

### 4 farklı sınıflanırma algoritması

In [3]:
names = ["Decision Tree", "RBF SVM", "Decision Tree"]
classifiers = [
    DecisionTreeClassifier(),
    SVC(gamma=2, C=1),
    DecisionTreeClassifier(max_depth=5)]

for name, clf in zip(names, classifiers):
    print("Algoritma:",name)
    clf.fit(X_train,y_train)
    y_test_pred = clf.predict(X_test)
    cm = confusion_matrix(y_test,y_test_pred)
    print('Egitim örnekleri')
    print(cm)

Algoritma: Decision Tree
Egitim örnekleri
[[1586   67]
 [  38 1609]]
Algoritma: RBF SVM
Egitim örnekleri
[[1643   10]
 [  58 1589]]
Algoritma: Decision Tree
Egitim örnekleri
[[1630   23]
 [  35 1612]]


### AdaBoost

In [4]:
for name, clf in zip(names, classifiers):
    print('-'*40)
    print("Algoritma:",name)
    bagging_clf = AdaBoostClassifier( base_estimator=clf,
                                    n_estimators=100,
                                    algorithm="SAMME")
    bagging_clf.fit(X_train,y_train)
    y_test_pred = bagging_clf.predict(X_test)
    cm = confusion_matrix(y_test,y_test_pred)
    print('Egitim örnekleri')
    print(cm)

----------------------------------------
Algoritma: Decision Tree
Egitim örnekleri
[[1586   67]
 [  38 1609]]
----------------------------------------
Algoritma: RBF SVM
Egitim örnekleri
[[   0 1653]
 [   0 1647]]
----------------------------------------
Algoritma: Decision Tree
Egitim örnekleri
[[1630   23]
 [  34 1613]]
