In [1]:
import numpy as np
import os
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error

In [19]:
# veri kumesini oku
kolon_adlari = ['duration','protocol_type','service','flag','src_bytes','dst_bytes','land','wrong_fragment','urgent',
'hot','num_failed_logins','logged_in','num_compromised','root_shell','su_attempted','num_root','num_file_creations',
'num_shells','num_access_files','num_outbound_cmds','is_host_login','is_guest_login','count','srv_count',
'serror_rate','srv_serror_rate','rerror_rate','srv_rerror_rate','same_srv_rate','diff_srv_rate','srv_diff_host_rate',
'dst_host_count','dst_host_srv_count','dst_host_same_srv_rate','dst_host_diff_srv_rate','dst_host_same_src_port_rate',
'dst_host_srv_diff_host_rate','dst_host_serror_rate','dst_host_srv_serror_rate','dst_host_rerror_rate',
'dst_host_srv_rerror_rate','label']

verikumesi = pd.read_csv("kddcup99.tar.gz",compression="gzip", names=kolon_adlari, 
low_memory=False, skiprows=1)

# ilgili kolonlari sec
secilecek_kolonlar = ['serror_rate','srv_serror_rate',
'rerror_rate','srv_rerror_rate','same_srv_rate','diff_srv_rate','srv_diff_host_rate','dst_host_count',
'dst_host_srv_count','dst_host_same_srv_rate','dst_host_diff_srv_rate','dst_host_same_src_port_rate',
'dst_host_srv_diff_host_rate','dst_host_serror_rate','dst_host_srv_serror_rate','dst_host_rerror_rate',
'dst_host_srv_rerror_rate']


X = verikumesi[secilecek_kolonlar].as_matrix()
y = verikumesi['label'].apply(lambda d:0 if d == 'normal.' else 1).as_matrix().astype(float )

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [21]:
X_train.shape

(330993, 17)

In [22]:
from sklearn.cluster import KMeans

In [23]:
kmeans = KMeans(n_clusters=2, random_state=0).fit(X_train)

In [24]:
from sklearn.metrics import completeness_score

In [26]:
y_pred = kmeans.predict(X_test).astype(float)
print(y_pred.dtype)
print(y_test.dtype)
print(kmeans.labels_.dtype)

print(completeness_score(y_pred,y_pred))
print(completeness_score(np.int32(y_test),y_pred))
print(completeness_score(y_test,y_test))


print(kmeans.labels_)
print(y_pred)
completeness_score(y_train, kmeans.labels_),

float64
float64
int32
pi.sum() 163027
pj.sum() 163027
outer [1287048228 1934328361]
4.004508723929665
pi.sum() 163027
pj.sum() 163027
outer [ -467043166 -1600081072  1414209055  1460914136]
nan
pi.sum() 163027
pj.sum() 163027
outer [1033944025  -52388800]
nan
[1 1 0 ... 0 1 1]
[0. 0. 1. ... 0. 1. 0.]


c:\users\user\appdata\local\programs\python\python35\lib\site-packages\sklearn\metrics\cluster\supervised.py:608: RuntimeWarning: invalid value encountered in log
  log_outer = -np.log(outer) + log(pi.sum()) + log(pj.sum())


pi.sum() 330993
pj.sum() 330993
outer [-1474722054  -305729725  1554811720 -1887143588]


(nan,)

In [13]:
np.unique(y_pred)

array([0, 1])

In [19]:
from sklearn.metrics import silhouette_samples, silhouette_score

In [21]:
silhouette_score(X_train,y_train)

MemoryError: 